### ISSUE TITLE
Publish docker image to github or dockerhub

### ISSUE THREAD

**Issue by TheZoker** [bandundu/email-archiver#1]
It would be nice to allow users to just pull the image from the registry instead of the need to build them every time

**Comment by jsaltzman** [comment]
Having issues building (probably user error), so would appreciate this as well. For example, there is no make command on unraid.

**Comment by bandundu** [comment]
Done, the readme is updated accordingly.

**Comment by killmasta93** [comment]
any updates on the docker compose? @bandundu
