### ISSUE TITLE
read only IMAP

### ISSUE THREAD

**Issue by cirrusflyer** [bandundu/email-archiver#11]
I'd like to use this to archive an IMAP mailbox, but with read only permissions.  Getting this error:

email-archiver-web-1  |     raise self.readonly('%s is not writable' % mailbox)
email-archiver-web-1  | imaplib.IMAP4.readonly: INBOX is not writable

Does the software need to have write access for some reason?

**Comment by bandundu** [comment]
This should be fixed now in https://github.com/bandundu/email-archiver/commit/691622aa33a47bebfa82b73122a09b9a06ed6225

**Comment by cirrusflyer** [comment]
Thanks.  Updated and attempts to work now, but getting this error:

email-archiver-web-1  | 2024-03-12 02:27:04,392 - ERROR - An error occurred during email archiving for account 1: expected string or bytes-like object
email-archiver-web-1  | 2024-03-12 02:27:04,394 - ERROR - Exception details: Traceback (most recent call last):
email-archiver-web-1  |   File "/app/email_archiver.py", line 159, in fetch_and_archive_emails
email-archiver-web-1  |     recipients_parts = email.header.decode_header(email_message['To'])
email-archiver-web-1  |   File "/usr/local/lib/python3.9/email/header.py", line 80, in decode_header
email-archiver-web-1  |     if not ecre.search(header):
email-archiver-web-1  | TypeError: expected string or bytes-like object

**Comment by bandundu** [comment]
I think this is the same error as in #12 and should be fixed. Please pull again, retry and let me know.

**Comment by cirrusflyer** [comment]
Better this time.  It was able to archive 1000 emails, but then hit the error:

email-archiver-web-1  | 2024-03-18 13:30:26,387 - ERROR - An error occurred during email archiving for account 1: 'NoneType' object is not subscriptable
email-archiver-web-1  | 2024-03-18 13:30:26,388 - ERROR - Exception details: Traceback (most recent call last):
email-archiver-web-1  |   File "/app/email_archiver.py", line 133, in fetch_and_archive_emails
email-archiver-web-1  |     raw_email = data[0][1]
email-archiver-web-1  | TypeError: 'NoneType' object is not subscriptable

**Comment by cirrusflyer** [comment]
And it looks like it did pull in all the emails from the Inbox folder.  I guess I forgot it can only do a single folder at a time.
