### ISSUE TITLE
ModuleNotFoundError: No module named 'flask_cors'

### ISSUE THREAD

**Issue by cirrusflyer** [bandundu/email-archiver#21]
Getting this error on a Raspberry Pi 4:

email-archiver-web-1  |   File "/app/app.py", line 8, in <module>
email-archiver-web-1  |     from flask_cors import CORS
email-archiver-web-1  | ModuleNotFoundError: No module named 'flask_cors'

**Comment by killmasta93** [comment]
same issue im having

**Comment by killmasta93** [comment]
instead of using the image i used the docker file and it worked
